I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 290, in script
    centred "{size=50}Конец!"
Exception: Sayer 'centred' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 290, in script
    centred "{size=50}Конец!"
  File "C:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'centred' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Код спасения pre_build
Mon Nov 27 15:32:28 2023
